---
- hosts: "{{ host }}"
  tasks:
   - name: Add RHEL 8 repository
     import_tasks: AddRepoRH8.yml
     when:
      - ansible_facts['distribution_major_version'] == "8"
      - ansible_facts['distribution'] == "RedHat"
     tags:
      - repo
   - name: Configure ntp
     import_role:
      name: rhel-system-roles.timesync
   - name: Install require binaries
     yum:
      name: 
       - tcsh
       - uuidd
       - util-linux
       - net-tools
       - cifs-utils
       - bind-utils
       - shadow-utils
       - yum-utils
       - libatomic
       - compat-sap-c++-9
       - libaio
       - libtool-ltdl
       - libnsl
      state: present
     tags:
      - prereq
   - name: disable firewalld service
     service:
      name: firewalld
      enabled: no
      state: stopped
   - name: Mount softwares from bpblfile server
     import_tasks: MountSoftware.yml
     tags:
      - mount
