---
- hosts: "{{ host }}"
  tasks:
   - yum_repository:
      name: local
      description: local
      baseurl: http://rhelrepo.bergerbd.com
      gpgcheck: no
   - name: Install require binaries
     yum:
      name: 
       - tcsh
       - uuidd
       - util-linux
       - net-tools
       - cifs-utils
       - bind-utils
       - shadow-utils
       - yum-utils
       - vim
       - ntpdate
       - libatomic
       - compat-sap-c++-7
       - libaio
       - libtool-ltdl
      state: present
   - service:
      name: firewalld
      enabled: no
      state: stopped
   - name: Mount azure storage
     import_tasks: MountAzure.yml
     tags:
      - mount
   - template:
      src: HanaInstallAzure.j2
      dest: ~/HanaInstall.sh
      mode: u+x,g+x,o+x
   - shell: ~/HanaInstall.sh
     ignore_errors: yes
     register: cmd1
   - debug: msg="{{ cmd1.stdout_lines }}"
...
