---
- hosts: "{{ host }}"
  user: root
  become_user: "{{ dbadm }}"
  gather_facts: yes
  tasks:
   - template:
      src: HanaDbStart.j2
      dest: ~/HanaDbStart.sh
      mode: u+x,g+x,o+x
   - shell: ~/HanaDbStart.sh
     ignore_errors: yes
     register: cmd2
   - debug: msg="{{ cmd2.stdout_lines }}"
...
