---
- hosts: "{{ host }}"
  user: root
  become_user: "{{ dbadm }}"
  gather_facts: yes
  tasks:
   - name: Restart Hana Database
     import_tasks: 
      - HanaDbStop.yml
      - HanaDbStart.yml
...
