---
- hosts: "{{ host }}"
  become: yes
  tasks:
   - name: Reconfigure grub
     shell: grub2-mkconfig -o /boot/grub2/grub.cfg
     tags:
      - execute
   - name: Reboot the machine (Wait for 2 min)
     reboot:
      reboot_timeout: 120
     tags:
      - execute
...
