---
- hosts: "{{ host }}"
  become: yes
  tasks:
   - name: Delete local repo
     file:
      path: /etc/yum.repos.d/local.repo
      state: absent
   - name: Remove subscription
     redhat_subscription:
      state: absent
   - name: Recursively remove directory
     file:
      path: /var/cache/yum
      state: absent
   - name: register rhsm
     redhat_subscription:
      state: present
      username: "{{ subsuser }}"
      password: "{{ subspwd }}"
      pool_ids: "{{ subspool }}"
      release: "7.7"
   - name: Disable repository
     rhsm_repository:
      name: '*'
      state: disabled
   - name: Enable repository
     rhsm_repository:
      name: "{{ item }}"
      state: enabled
     loop:
      - rhel-7-server-e4s-rpms
      - rhel-sap-for-rhel-7-server-e4s-rpms
      - rhel-sap-hana-for-rhel-7-server-e4s-rpms
      - rhel-7-server-extras-rpms
   - name: Run yum update
     yum:
      name: "*"
      releasever: "7.7"
      state: latest
     notify: Reboot the machine (Wait for 2 min)
  handlers:
   - name: Reboot the machine (Wait for 2 min)
     reboot:
      reboot_timeout: 120
...
